ui: tape
browsers:
  - name: chrome
    version: 30..latest
  - name: firefox
    version: 4..latest
  - name: safari
    version: 6..latest
  - name: ie
    version: 6..latest
  - name: opera
    version: 12..latest
  - name: iphone
    version: 6.1..latest
  - name: ipad
    version: 6.1..latest
  - name: android
    version: 4.2..latest
